# Generated by Django 4.2.13 on 2024-10-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_favoritebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('business', 'ビジネス'), ('life', '生活'), ('Python', 'Python'), ('Django', 'Django'), ('Ruby', 'Ruby'), ('Rails', 'Rails'), ('Java', 'Java'), ('Spring', 'Spring'), ('HTML/CSS', 'HTML/CSS'), ('JavaScript', 'JavaScript'), ('Vue.js', 'Vue.js'), ('React', 'React'), ('Angular', 'Angular'), ('PHP', 'PHP'), ('Laravel', 'Laravel'), ('C++', 'C++'), ('C#', 'C#'), ('Unity', 'Unity'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin'), ('Go', 'Go'), ('Rust', 'Rust'), ('SQL', 'SQL'), ('NoSQL', 'NoSQL'), ('other', 'その他')], max_length=100),
        ),
    ]
