# Generated by Django 4.2.13 on 2024-10-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
