# Generated by Django 4.2.13 on 2024-10-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_like_like_like_unique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
