# Generated by Django 4.2.13 on 2024-10-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
